### ISSUE TITLE
ArgoCD Version 5.6.5 and OTC CCE v1.23 are not compatible?

### ISSUE THREAD

**Issue by Pascal-Orthopy** [iits-consulting/terraform-argocd-bootstrap#6]
Hi,

after using the ArgoCD Terraform module (5.6.5) we have problems with ArgoCD and the `registry-creds` in our OTC CCE v1.23.

## ArgoCD
Here the problem is that ArgoCD chart of the latest version can not establish
connection with GitHub, which is a known problem (https://github.com/argoproj/argo-cd/issues/10490 and https://github.com/argoproj/argo-cd/issues/9809#issuecomment-1298785315).
To fix it one should delete `seccompProfile` from argocd-server deployment.

## Registry-Creds
The problem here is that the default role for service account needs `lease` access to be able to start the operator. This could be fixed by adding
```yaml
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
```
to role `rules`.

Are these Problem known and are there solutions? Maybe we have missed some configuration?

Greets
